# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Report the version of kastore C API
#'
#' @details The version is defined by kastore in the header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'     \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_tskitr_kastore_version`)
}

#' Report the version of tskit C API
#'
#' @details The version is defined by tskit in the header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'     \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_tskitr_tskit_version`)
}

#' Load tree sequence from a file
#'
#' @param file a string specifying the full path of the tree sequence file.
#' @return An external pointer to a \code{tsk_treeseq_t} object.
#' @examples
#' ts_file <- system.file("examples", "test.trees", package = "tskitr")
#' ts <- treeseq_load(ts_file)
#' ts
#' is(ts)
#' treeseq_num_nodes(ts)
#' try(treeseq_load())
#' try(treeseq_load("nonexistent.trees"))
#' @export
treeseq_load <- function(file) {
    .Call(`_tskitr_treeseq_load`, file)
}

#' Get number of nodes in a tree sequence
#'
#' @param ts an external pointer to a \code{tsk_treeseq_t} object.
#' @return An integer specifying the number of nodes in the tree sequence.
#' @examples
#' ts_file <- system.file("examples", "test.trees", package = "tskitr")
#' ts <- treeseq_load(ts_file)
#' treeseq_num_nodes(ts)
#' n <- treeseq_num_nodes(ts)
#' n
#' is(n)
#' try(treeseq_num_nodes())
#' try(treeseq_num_nodes(nonexistent_ts))
#' @export
treeseq_num_nodes <- function(ts) {
    .Call(`_tskitr_treeseq_num_nodes`, ts)
}

