// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kastore_version
Rcpp::IntegerVector kastore_version();
RcppExport SEXP _tskitr_kastore_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(kastore_version());
    return rcpp_result_gen;
END_RCPP
}
// tskit_version
Rcpp::IntegerVector tskit_version();
RcppExport SEXP _tskitr_tskit_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(tskit_version());
    return rcpp_result_gen;
END_RCPP
}
// treeseq_load
SEXP treeseq_load(std::string file);
RcppExport SEXP _tskitr_treeseq_load(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    rcpp_result_gen = Rcpp::wrap(treeseq_load(file));
    return rcpp_result_gen;
END_RCPP
}
// treeseq_num_nodes
int treeseq_num_nodes(SEXP ts);
RcppExport SEXP _tskitr_treeseq_num_nodes(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(treeseq_num_nodes(ts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tskitr_kastore_version", (DL_FUNC) &_tskitr_kastore_version, 0},
    {"_tskitr_tskit_version", (DL_FUNC) &_tskitr_tskit_version, 0},
    {"_tskitr_treeseq_load", (DL_FUNC) &_tskitr_treeseq_load, 1},
    {"_tskitr_treeseq_num_nodes", (DL_FUNC) &_tskitr_treeseq_num_nodes, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tskitr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
